# 🔧 Pipelines de datos para ML con Airflow

<table style='width:100%; border-collapse:collapse; background:#f0f4f8; border-radius:10px; overflow:hidden; margin-bottom:12px;'>
<tr>
<td style='padding:14px; text-align:center; border-right:1px solid #d0d7de;'><b>⏱️ Duración</b><br>15 minutos</td>
<td style='padding:14px; text-align:center; border-right:1px solid #d0d7de;'><b>🎯 Modalidad</b><br>Demo práctica en vivo</td>
<td style='padding:14px; text-align:center; border-right:1px solid #d0d7de;'><b>📊 Nivel</b><br>Intermedio</td>
<td style='padding:14px; text-align:center;'><b>🧰 Herramientas</b><br>Python · scikit-learn · Airflow</td>
</tr>
</table>

---

## 🎯 Al finalizar esta clase, vas a poder:

1. Identificar qué es un **pipeline de ML** y por qué es necesario en producción
2. Construir un pipeline completo paso a paso en Python
3. Explicar por qué un script manual **no alcanza** para automatizar procesos reales
4. Entender los tres pilares de **Apache Airflow**: DAG, Task y Scheduler

---

## 📋 Agenda

| # | Tema | ⏱️ Tiempo |
|---|------|-----------|
| 1 | 🚀 Bienvenida y activación | 1.5 min |
| 2 | 🏢 El problema de negocio | 2 min |
| 3 | 🔨 Construimos el pipeline en Python | 5 min |
| 4 | ⚠️ ¿Por qué no alcanza un script? | 2 min |
| 5 | 🌬️ Airflow: conceptos + demo en vivo | 3 min |
| 6 | ✅ Cierre y reflexión | 1.5 min |

---

> 📌 **Prerrequisitos:** 
- Python básico (funciones, DataFrames con pandas)
- Noción de qué es un modelo de ML.
- Versionamiento con Git.
- No se requiere experiencia previa con Airflow.

---

# 🟢 INICIO — ⏱️ 1:30 min

<div style='background:#e8f5e9; border-left:5px solid #4caf50; padding:16px; border-radius:8px; margin:12px 0;'>

### 📷 Activación

Voy a hacer algunas preguntas. Si tu respuesta es **SÍ**, encendé la cámara por 3 segundos.

- ¿Alguna vez corriste manualmente un script de Python todos los días?
- ¿Escuchaste hablar de Airflow antes de hoy?
- ¿Qué es Churn?

</div>

<div style='background:#fff8e1; border-left:5px solid #ffc107; padding:16px; border-radius:8px; margin:12px 0;'>

### 💬 Respondan en una palabra:

**¿Qué herramienta usarían para automatizar un proceso de datos que debe correr todos los días a las 6 AM?**

</div>

---

# 🏢 El problema de negocio — ⏱️ 2:00 min

Somos el equipo de datos de una empresa de telecomunicaciones.

<div style='display:flex; gap:12px; margin:16px 0; flex-wrap:wrap;'>
<div style='flex:1; min-width:140px; padding:16px; background:#e3f2fd; border-radius:10px; text-align:center;'>
<div style='font-size:28px; font-weight:bold; color:#1976d2;'>7,043</div>
<div style='color:#555;'>clientes activos</div>
</div>
<div style='flex:1; min-width:140px; padding:16px; background:#fce4ec; border-radius:10px; text-align:center;'>
<div style='font-size:28px; font-weight:bold; color:#c62828;'>26.5%</div>
<div style='color:#555;'>tasa de cancelación mensual</div>
</div>
<div style='flex:1; min-width:140px; padding:16px; background:#e8f5e9; border-radius:10px; text-align:center;'>
<div style='font-size:28px; font-weight:bold; color:#2e7d32;'>6:00 AM</div>
<div style='color:#555;'>hora límite para la lista</div>
</div>
</div>

<div style='background:#fff3e0; border-left:5px solid #ff9800; padding:18px; border-radius:8px; margin:16px 0;'>

💼 **El CEO nos dice:**

*"Equipo: para proteger nuestros ingresos, necesito que el equipo comercial inicie su jornada a las **6:00 AM** con una **lista priorizada de clientes con mayor riesgo de fuga** para contactarlos de forma preventiva. Y dado que operamos en un sector muy dinámico, el sistema debe actualizarse automáticamente."*

</div>

<div style='background:#fce4ec; border-left:5px solid #e91e63; padding:16px; border-radius:8px; margin:12px 0;'>

### Antes de continuar:

🤔 **¿Quién corre este proceso todos los días a las 6 AM?**

🤔 **¿Cómo sabe un modelo matemático que el mercado cambió ayer?**

</div>

---

# 🔨 Construimos el pipeline — ⏱️ 5:00 min

Para cumplir el pedido del CEO, necesitamos ejecutar **6 pasos en orden** todos los días:

<div style='display:flex; flex-wrap:wrap; align-items:center; justify-content:center; gap:6px; padding:20px; background:#f8f9fa; border-radius:12px; margin:16px 0; border:1px solid #e0e0e0;'>

<div style='text-align:center; padding:12px 14px; background:#e3f2fd; border:2px solid #1976d2; border-radius:10px; min-width:85px;'>
<div style='font-size:20px;'>📥</div>
<div style='font-weight:bold; font-size:12px;'>extract_data</div>
<div style='font-size:11px; color:#666;'>Leer clientes</div>
</div>

<div style='font-size:20px; color:#1976d2; font-weight:bold;'>→</div>

<div style='text-align:center; padding:12px 14px; background:#e3f2fd; border:2px solid #1976d2; border-radius:10px; min-width:85px;'>
<div style='font-size:20px;'>🧹</div>
<div style='font-weight:bold; font-size:12px;'>clean_data</div>
<div style='font-size:11px; color:#666;'>Limpiar datos</div>
</div>

<div style='font-size:20px; color:#1976d2; font-weight:bold;'>→</div>

<div style='text-align:center; padding:12px 14px; background:#e3f2fd; border:2px solid #1976d2; border-radius:10px; min-width:85px;'>
<div style='font-size:20px;'>⚙️</div>
<div style='font-weight:bold; font-size:12px;'>feature_engineering</div>
<div style='font-size:11px; color:#666;'>Transformar</div>
</div>

<div style='font-size:20px; color:#1976d2; font-weight:bold;'>→</div>

<div style='text-align:center; padding:12px 14px; background:#e3f2fd; border:2px solid #1976d2; border-radius:10px; min-width:85px;'>
<div style='font-size:20px;'>🤖</div>
<div style='font-weight:bold; font-size:12px;'>train_model</div>
<div style='font-size:11px; color:#666;'>Entrenar</div>
</div>

<div style='font-size:20px; color:#1976d2; font-weight:bold;'>→</div>

<div style='text-align:center; padding:12px 14px; background:#e3f2fd; border:2px solid #1976d2; border-radius:10px; min-width:85px;'>
<div style='font-size:20px;'>📊</div>
<div style='font-weight:bold; font-size:12px;'>evaluate_model</div>
<div style='font-size:11px; color:#666;'>Medir calidad</div>
</div>

<div style='font-size:20px; color:#1976d2; font-weight:bold;'>→</div>

<div style='text-align:center; padding:12px 14px; background:#c8e6c9; border:2px solid #388e3c; border-radius:10px; min-width:85px;'>
<div style='font-size:20px;'>📋</div>
<div style='font-weight:bold; font-size:12px;'>generate_predictions</div>
<div style='font-size:11px; color:#666;'>Lista de riesgo</div>
</div>

<div style='font-size:20px; color:#388e3c; font-weight:bold;'>→</div>

<div style='text-align:center; padding:12px 14px; background:#f3e5f5; border:2px solid #7b1fa2; border-radius:10px; min-width:85px;'>
<div style='font-size:20px;'>📞</div>
<div style='font-weight:bold; font-size:12px;'>Equipo Comercial</div>
<div style='font-size:11px; color:#666;'>Contacta clientes</div>
</div>

</div>

Vamos a construir cada función, **una por una**.

In [1]:
# ── Dependencias ──────────────────────────────────────────────────────────────
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report

DATA_PATH    = "../data/raw/Telco_customer_churn.xlsx"
PROCESSED_DIR = "../data/processed"

## 📥 Paso 1 — `extract_data()`

Lee la base de clientes desde la fuente de datos.

> 💡 En producción, esta función conectaría a una base de datos, un data lake o una API. Hoy usamos un Excel como proxy de esa fuente.

In [2]:
def extract_data() -> pd.DataFrame:
    df = pd.read_excel(DATA_PATH)
    print(f"✅ extract_data | {len(df):,} clientes cargados | {df.shape[1]} columnas")
    return df

df_raw = extract_data()
df_raw.head(3)

✅ extract_data | 7,043 clientes cargados | 33 columnas

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved

## 🧹 Paso 2 — `clean_data(df)`

Corrige tipos de datos, maneja nulos y estandariza valores.

> 💡 **Dato real del dataset:** algunos clientes nuevos tienen `Total Charges` como texto vacío porque llevan 0 meses de antigüedad. Si no lo corregimos, el modelo entrena con un dato roto sin que nadie lo sepa.

In [9]:
def clean_data(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()

    # Total Charges viene como string con espacios en blanco en algunos registros
    df["Total Charges"] = pd.to_numeric(df["Total Charges"], errors="coerce")

    # Clientes nuevos (Tenure = 0) tienen Total Charges nulo → rellenar con Monthly Charges
    df["Total Charges"] = df["Total Charges"].fillna(df["Monthly Charges"])

    # Churn Reason solo tiene valor para churners
    df["Churn Reason"] = df["Churn Reason"].fillna("No churn")

    nulls_remaining = df.isnull().sum().sum()
    print(f"✅ clean_data | Nulos restantes: {nulls_remaining}")
    return df

df_clean = clean_data(df_raw)

✅ clean_data | Nulos restantes: 0

<div style='background:#e3f2fd; border-left:5px solid #1976d2; padding:16px; border-radius:8px; margin:12px 0;'>

### 💬 Chat:

¿Qué creen que pasa si **saltamos la limpieza** y entrenamos el modelo con los datos sucios?

¿Cómo nos daríamos cuenta del error? ¿El CEO lo sabría?

</div>

## ⚙️ Paso 3 — `feature_engineering(df)`

Transforma variables categóricas y selecciona las features relevantes para el modelo.

> 💡 Los modelos de ML solo entienden números. Necesitamos convertir `"Month-to-month"`, `"Electronic check"`, `"Female"` → valores numéricos. Eso hace `LabelEncoder`.

In [10]:
CATEGORICAL_FEATURES = [
    "Gender", "Senior Citizen", "Partner", "Dependents",
    "Phone Service", "Multiple Lines", "Internet Service",
    "Online Security", "Online Backup", "Device Protection",
    "Tech Support", "Streaming TV", "Streaming Movies",
    "Contract", "Paperless Billing", "Payment Method",
]
NUMERIC_FEATURES = ["Tenure Months", "Monthly Charges", "Total Charges"]
TARGET = "Churn Value"

def feature_engineering(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    le = LabelEncoder()
    for col in CATEGORICAL_FEATURES:
        df[col] = le.fit_transform(df[col].astype(str))
    features = CATEGORICAL_FEATURES + NUMERIC_FEATURES + [TARGET]
    df_model = df[features]
    print(f"✅ feature_engineering | {len(CATEGORICAL_FEATURES)} features categóricas encodadas | shape: {df_model.shape}")
    return df_model

df_features = feature_engineering(df_clean)
df_features.head(3)

✅ feature_engineering | 16 features categóricas encodadas | shape: (7043, 20)

,Gender,Senior Citizen,Partner,Dependents,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Tenure Months,Monthly Charges,Total Charges,Churn Value
0,1,0,0,0,1,0,0,2,2,0,0,0,0,0,1,3,2,53.85,108.15,1
1,0,0,0,1,1,0,1,0,0,0,0,0,0,0,1,2,2,70.70,151.65,1
2,0,0,0,1,1,2,1,0,0,2,0,2,2,0,1,2,8,99.65,820.50,1

## 🤖 Paso 4 — `train_model(df)`

Entrena un **Random Forest** para predecir qué clientes van a cancelar el servicio.

> 💡 El Random Forest es como un comité de decisión: entrena 100 árboles distintos y vota. Más robusto que un solo árbol y muy difícil de sobreajustar.

In [11]:
def train_model(df: pd.DataFrame):
    X = df.drop(columns=[TARGET])
    y = df[TARGET]
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    # Persistir splits en data/processed/
    X_train.to_csv(f"{PROCESSED_DIR}/X_train.csv", index=True)
    X_test.to_csv(f"{PROCESSED_DIR}/X_test.csv",  index=True)
    y_train.to_csv(f"{PROCESSED_DIR}/y_train.csv", index=True)
    y_test.to_csv(f"{PROCESSED_DIR}/y_test.csv",  index=True)

    model = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
    model.fit(X_train, y_train)

    print(f"✅ train_model | Entrenado con {len(X_train):,} registros | Test: {len(X_test):,}")
    print(f"   💾 Splits guardados en {PROCESSED_DIR}/")
    return model, X_test, y_test

model, X_test, y_test = train_model(df_features)

✅ train_model | Entrenado con 5,634 registros | Test: 1,409
   💾 Splits guardados en ../data/processed/

## 📊 Paso 5 — `evaluate_model(model, X_test, y_test)`

Mide qué tan bien predice nuestro modelo antes de enviarlo al equipo comercial.

> 💡 No solo nos importa la **accuracy** (exactitud global). Para un problema de churn nos importa más el **recall**: ¿qué porcentaje de clientes que *van a cancelar* logramos detectar?

In [12]:
def evaluate_model(model, X_test: pd.DataFrame, y_test: pd.Series) -> None:
    y_pred = model.predict(X_test)
    print("✅ evaluate_model\n")
    print(classification_report(y_test, y_pred, target_names=["No Churn", "Churn"]))

evaluate_model(model, X_test, y_test)

✅ evaluate_model

              precision    recall  f1-score   support

    No Churn       0.83      0.90      0.86      1035
       Churn       0.64      0.51      0.56       374

    accuracy                           0.79      1409
   macro avg       0.73      0.70      0.71      1409
weighted avg       0.78      0.79      0.78      1409

## 📋 Paso 6 — `generate_predictions(model, X_test, df_original)`

Genera la lista de clientes con mayor probabilidad de cancelar el servicio.

> 💡 Notar que necesitamos tanto el **modelo** (para las probabilidades) como el **DataFrame limpio original** (para recuperar `CustomerID`, `City`, `Contract` — columnas que fueron descartadas en el paso de features). Eso explica la doble dependencia que veremos luego en Airflow.

In [7]:
def generate_predictions(model, X_test: pd.DataFrame, df_original: pd.DataFrame, top_n: int = 20) -> pd.DataFrame:
    probs  = model.predict_proba(X_test)[:, 1]
    result = df_original.loc[X_test.index, ["CustomerID", "City", "Contract", "Monthly Charges"]].copy()
    result["churn_probability"] = probs
    result["churn_probability"] = result["churn_probability"].map("{:.1%}".format)
    print("✅ generate_predictions")
    return result.reset_index(drop=True)

predictions = generate_predictions(model, X_test, df_clean)
predictions

✅ generate_predictions

,CustomerID,City,Contract,Monthly Charges,churn_probability
0,4376-KFVRS,Barstow,Two year,114.05,0.0%
1,2754-SDJRD,Somis,Month-to-month,100.15,84.0%
2,9917-KWRBE,Anaheim,One year,78.35,8.0%
3,0365-GXEZS,Copperopolis,Month-to-month,78.20,34.0%
4,9385-NXKDA,Hesperia,Two year,82.65,2.0%
...,...,...,...,...,...
1404,5204-HMGYF,La Crescenta,One year,87.20,3.0%
1405,9950-MTGYX,San Jose,Two year,20.30,0.0%
1406,3675-EQOZA,Newport Beach,Month-to-month,20.65,8.0%
1407,3646-ITDGM,Sacramento,Two year,19.70,17.0%
1408,3913-FCUUW,Hanford,Two year,70.45,0.0%

---

# 🔗 El pipeline completo

Las 6 funciones encadenadas — exactamente lo que el CEO necesita correr **todos los días a las 6:00 AM**:

In [8]:
df                    = extract_data()
df                    = clean_data(df)
df_model              = feature_engineering(df)
model, X_test, y_test = train_model(df_model)
evaluate_model(model, X_test, y_test)
predictions           = generate_predictions(model, X_test, df)

print("\n📋 Lista lista para el equipo comercial:")
predictions

✅ extract_data | 7,043 clientes cargados | 33 columnas
✅ clean_data | Nulos restantes: 0
✅ feature_engineering | 16 features categóricas encodadas | shape: (7043, 20)
✅ train_model | Entrenado con 5,634 registros | Test: 1,409
   💾 Splits guardados en ../data/processed/
✅ evaluate_model

              precision    recall  f1-score   support

    No Churn       0.83      0.90      0.86      1035
       Churn       0.64      0.51      0.56       374

    accuracy                           0.79      1409
   macro avg       0.73      0.70      0.71      1409
weighted avg       0.78      0.79      0.78      1409

✅ generate_predictions

📋 Lista lista para el equipo comercial:

,CustomerID,City,Contract,Monthly Charges,churn_probability
0,4376-KFVRS,Barstow,Two year,114.05,0.0%
1,2754-SDJRD,Somis,Month-to-month,100.15,84.0%
2,9917-KWRBE,Anaheim,One year,78.35,8.0%
3,0365-GXEZS,Copperopolis,Month-to-month,78.20,34.0%
4,9385-NXKDA,Hesperia,Two year,82.65,2.0%
...,...,...,...,...,...
1404,5204-HMGYF,La Crescenta,One year,87.20,3.0%
1405,9950-MTGYX,San Jose,Two year,20.30,0.0%
1406,3675-EQOZA,Newport Beach,Month-to-month,20.65,8.0%
1407,3646-ITDGM,Sacramento,Two year,19.70,17.0%
1408,3913-FCUUW,Hanford,Two year,70.45,0.0%

---

# ⚠️ ¿Por qué esto no es suficiente? — ⏱️ 2:00 min

El pipeline **funciona**. ✅  Pero tiene **5 problemas reales** en producción:

<table style='width:100%; border-collapse:collapse; margin:16px 0;'>
<thead>
<tr style='background:#ffebee;'>
<th style='padding:12px; text-align:left; border-bottom:2px solid #ef9a9a;'>❌ Problema</th>
<th style='padding:12px; text-align:left; border-bottom:2px solid #ef9a9a;'>💥 Consecuencia en producción</th>
</tr>
</thead>
<tbody>
<tr style='border-bottom:1px solid #eee;'>
<td style='padding:11px;'>No tiene scheduling</td>
<td style='padding:11px;'>Alguien tiene que despertarse a las 5:55 AM para ejecutarlo manualmente</td>
</tr>
<tr style='border-bottom:1px solid #eee; background:#fafafa;'>
<td style='padding:11px;'>Si falla el Paso 2, los Pasos 3-6 siguen corriendo</td>
<td style='padding:11px;'>El modelo se entrena con datos sucios sin que nadie lo sepa</td>
</tr>
<tr style='border-bottom:1px solid #eee;'>
<td style='padding:11px;'>No hay logs ni alertas</td>
<td style='padding:11px;'>Nadie sabe que falló hasta que el CEO pregunta a las 8 AM</td>
</tr>
<tr style='border-bottom:1px solid #eee; background:#fafafa;'>
<td style='padding:11px;'>No hay reintentos automáticos</td>
<td style='padding:11px;'>Un corte de red cancela todo el proceso</td>
</tr>
<tr>
<td style='padding:11px;'>No escala</td>
<td style='padding:11px;'>Con 10 pipelines distintos, el caos es total</td>
</tr>
</tr>
<tr style='border-bottom:1px solid #eee;'>
<td style='padding:11px;'>No hay registros de tiempos</td>
<td style='padding:11px;'>Nadie sabe dónde esta el cuello de botella</td>
</tr>
</tbody>
</table>

<div style='background:#fce4ec; border-left:5px solid #e91e63; padding:16px; border-radius:8px; margin:12px 0;'>

### 💬 Chat:

Si `clean_data` falla a las 5:58 AM... ¿queremos que `train_model` siga ejecutándose con datos sin limpiar?

**¿Qué necesitamos para resolver todos estos problemas?**

**¿Es necesario entrenar el modelo todos los días?**

</div>

> ### Necesitamos un **orquestador de pipelines**.

---

# 🌬️ Airflow al rescate — ⏱️ 3:00 min

**Apache Airflow** es un orquestador de pipelines open-source. Agrega exactamente lo que nuestro script no tiene.

## Tres conceptos clave

<div style='display:flex; gap:14px; margin:16px 0; flex-wrap:wrap;'>

<div style='flex:1; min-width:160px; padding:16px; background:#e3f2fd; border-radius:10px; border-top:4px solid #1976d2;'>
<b style='font-size:15px;'>📐 DAG</b><br>
<i style='color:#555;'>Directed Acyclic Graph</i><br><br>
El pipeline completo con sus dependencias, definido como código.<br><br>
<b>Analogía:</b> el plano de la fábrica.
</div>

<div style='flex:1; min-width:160px; padding:16px; background:#e8f5e9; border-radius:10px; border-top:4px solid #388e3c;'>
<b style='font-size:15px;'>⚙️ Task</b><br>
<i style='color:#555;'>Tarea individual</i><br><br>
Cada función del pipeline (<code>extract_data</code>, <code>clean_data</code>…).<br><br>
<b>Analogía:</b> una máquina en la fábrica.
</div>

<div style='flex:1; min-width:160px; padding:16px; background:#fff3e0; border-radius:10px; border-top:4px solid #ff9800;'>
<b style='font-size:15px;'>⏰ Scheduler</b><br>
<i style='color:#555;'>Motor de ejecución</i><br><br>
Ejecuta el DAG según el horario y gestiona reintentos automáticos.<br><br>
<b>Analogía:</b> el turno de trabajo.
</div>

</div>

---

## Las mismas funciones, ahora como DAG

```python
from airflow.decorators import dag, task
import pendulum

@dag(
    schedule="0 6 * * *",    # todos los días a las 6:00 AM
    start_date=pendulum.datetime(2024, 1, 1),
    catchup=False
)
def churn_pipeline():

    @task
    def extract():              return pipeline.extract_data()

    @task
    def clean(df):              return pipeline.clean_data(df)

    @task
    def engineer(df):           return pipeline.feature_engineering(df)

    @task
    def train(df_features):     return pipeline.train_model(df_features)

    @task
    def evaluate(trained):      pipeline.evaluate_model(...)

    @task
    def generate(trained, df_clean): return pipeline.generate_predictions(...)

    # Airflow construye el grafo de dependencias automáticamente:
    raw      = extract()
    clean_df = clean(raw)
    features = engineer(clean_df)
    trained  = train(features)
    evaluate(trained)
    generate(trained, clean_df)   # ← depende de train Y de clean

churn_pipeline()
```

<div style='background:#e8f5e9; border-left:5px solid #4caf50; padding:14px; border-radius:8px; margin:16px 0;'>

💡 **¿Notaron algo?** Es el **mismo código** del notebook, envuelto en decoradores `@task`.
El orquestador no cambia la lógica del pipeline — solo agrega scheduling, dependencias, logs y reintentos.

</div>

<div style='background:#fce4ec; border-left:5px solid #e53935; padding:14px; border-radius:8px; margin:16px 0;'>

⚠️ **Limitación de este demo:** estamos corriendo Airflow localmente. En la práctica, los pipelines se despliegan en un **ambiente cloud** (AWS MWAA, Google Cloud Composer, Astronomer, etc.), de modo que el scheduler vive en infraestructura gestionada y las ejecuciones no dependen de que tu máquina local esté encendida.

</div>

---

# 🖥️ Demo en vivo — Airflow UI

Abrimos `http://localhost:8080` → usuario `admin` / contraseña `admin`

<table style='width:100%; border-collapse:collapse; margin:16px 0;'>
<thead>
<tr style='background:#e3f2fd;'>
<th style='padding:11px; text-align:left; border-bottom:2px solid #90caf9;'>Paso</th>
<th style='padding:11px; text-align:left; border-bottom:2px solid #90caf9;'>Qué mostrar</th>
<th style='padding:11px; text-align:left; border-bottom:2px solid #90caf9;'>Concepto que refuerza</th>
</tr>
</thead>
<tbody>
<tr style='border-bottom:1px solid #eee;'>
<td style='padding:11px;'>1️⃣</td>
<td style='padding:11px;'><b>Graph View</b> del DAG <code>churn_pipeline</code></td>
<td style='padding:11px;'>Las mismas 6 tasks del notebook, ahora como grafo visual</td>
</tr>
<tr style='border-bottom:1px solid #eee; background:#fafafa;'>
<td style='padding:11px;'>2️⃣</td>
<td style='padding:11px;'><b>Trigger DAG</b> → tasks ejecutándose en verde una por una</td>
<td style='padding:11px;'>Scheduling y ejecución automática con dependencias</td>
</tr>
<tr style='border-bottom:1px solid #eee;'>
<td style='padding:11px;'>3️⃣</td>
<td style='padding:11px;'><b>Logs</b> de una task → mismo output que vimos arriba</td>
<td style='padding:11px;'>Trazabilidad y debugging por tarea individual</td>
</tr>
<tr>
<td style='padding:11px;'>4️⃣</td>
<td style='padding:11px;'>Activar <code>FAIL_CLEAN = true</code> → tasks posteriores bloqueadas</td>
<td style='padding:11px;'>Gestión de dependencias: si falla <code>clean</code>, no se entrena</td>
</tr>
</tbody>
</table>

<div style='background:#fce4ec; border-left:5px solid #e91e63; padding:16px; border-radius:8px; margin:16px 0;'>

### 💬 Pregunta para el chat:

¿Tiene sentido entrenar el modelo si la limpieza de datos falló?

→ Airflow entiende las dependencias y **evita ejecutar lo que no tiene sentido ejecutar**.

</div>

---

# ✅ CIERRE — ⏱️ 1:30 min

## Lo que construimos hoy

1. ✅ Definimos el **problema de negocio**: predecir churn automáticamente a las 6 AM
2. ✅ Construimos un **pipeline de ML en Python** con 6 funciones encadenadas
3. ✅ Identificamos **5 limitaciones reales** de un script manual en producción
4. ✅ Aprendimos los 3 conceptos clave de Airflow: **DAG, Task y Scheduler**
5. ✅ Vimos el **mismo pipeline corriendo orquestado** en la UI de Airflow

---

## 🎤 Reflexión final — Chat

<div style='background:#f3e5f5; border-left:5px solid #7b1fa2; padding:18px; border-radius:8px; margin:12px 0;'>

Completen una de estas frases en el chat:

**"Antes de hoy pensaba que para automatizar datos alcanzaba con..."**

**"Ahora entiendo que en producción se necesita..."**

</div>

---

## 🚀 Pregunta final

<div style='background:#e8f5e9; border-left:5px solid #4caf50; padding:20px; border-radius:10px; margin:12px 0; text-align:center;'>

**Si mañana este proceso debe correr automáticamente a las 6:00 AM, notificar cuando falle una tarea, y reintentar sola si hay un error de red...**

### ¿Usarían un script manual o un orquestador como Airflow?

</div>

---

> 📚 **Para seguir aprendiendo:**
> - Documentación oficial: [airflow.apache.org](https://airflow.apache.org)
> - El DAG completo de esta clase: `dags/churn_pipeline_dag.py`
> - Para correr Airflow localmente: `./run_airflow.sh`